### ISSUE TITLE
Cannot use ecto.gen.migration with jsroutes configured in the compilers

### ISSUE THREAD

**Issue by ghost** [tiagoengel/phoenix-jsroutes#4]
When I try use "mix ecto.gen.migration file_name" with jsroutes configured in project, mix raise this error: "(Mix) module Elixir.file_name was not loaded and cannot be loaded"

---

➜  systextil-ddp git:(master) ✗ mix ecto.gen.migration add_project_tag_color
*\* (Mix) module Elixir.add_project_tag_color was not loaded and cannot be loaded

**Comment by diogovk** [comment]
Wrong project?

**Comment by tiagoengel** [comment]
No, that's a bug. The compiler task considers the first argument as a module name when it does not start with `-` and mix pass along the arguments to the dependant tasks, so the compiler is trying to compile the `add_project_tag_color` module which does not exist.

I think the best way to solve this is to use a parameter (`--router RouterName` for instance) instead of relying on the first argument.

**Comment by tiagoengel** [comment]
I just publish the version 0.0.3 with a fix for this error.
